import { defineField, defineType } from 'sanity'

export const awardEventType = defineType({
  name: 'awardEvent',
  title: 'Award Event',
  type: 'document',
  fields: [
    defineField({
      name: 'eventYear',
      title: 'Event Year',
      type: 'number',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'eventTitle',
      title: 'Event Title',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'eventSubtitle',
      title: 'Event Subtitle',
      type: 'string',
    }),
    defineField({
      name: 'eventDate',
      title: 'Event Date',
      type: 'datetime',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'eventLocation',
      title: 'Event Location',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'eventVenue',
      title: 'Event Venue',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'isActive',
      title: 'Is Active Event',
      type: 'boolean',
      description: 'Mark as active to show this event on the website',
      initialValue: true,
    }),
    defineField({
      name: 'status',
      title: 'Event Status',
      type: 'string',
      options: {
        list: [
          {title: 'Nominations Open', value: 'nominations_open'},
          {title: 'Nominations Closed', value: 'nominations_closed'},
          {title: 'Awards Announced', value: 'awards_announced'},
          {title: 'Event Completed', value: 'event_completed'},
          {title: 'Planning', value: 'planning'},
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'yearsStrong',
      title: 'Years Strong',
      type: 'number',
      description: 'Number of years SEED has been running',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'primaryColor',
      title: 'Primary Color',
      type: 'string',
      description: 'Primary color for the event (hex code)',
      initialValue: '#6366f1',
    }),
    defineField({
      name: 'secondaryColor',
      title: 'Secondary Color',
      type: 'string',
      description: 'Secondary color for the event (hex code)',
      initialValue: '#818cf8',
    }),
    defineField({
      name: 'accentColor',
      title: 'Accent Color',
      type: 'string',
      description: 'Accent color for the event (hex code)',
      initialValue: '#4f46e5',
    }),
    defineField({
      name: 'registerEnabled',
      title: 'Registration Enabled',
      type: 'boolean',
      description: 'Enable registration for this event',
      initialValue: false,
    }),
    defineField({
      name: 'registrationUrl',
      title: 'Registration URL',
      type: 'url',
      hidden: ({parent}) => !parent?.registerEnabled,
    }),
    defineField({
      name: 'bannerConfig',
      title: 'Banner Configuration',
      type: 'object',
      description: 'Choose banner type: countdown (event ongoing), announcement (honorees), or custom slides.',
      fields: [
        defineField({
          name: 'bannerType',
          title: 'Banner Type',
          type: 'string',
          description: 'Countdown = timer + registration. Announcement = honorees + event details. Custom = your own slides.',
          options: {
            list: [
              { title: 'Countdown', value: 'countdown' },
              { title: 'Announcement', value: 'announcement' },
              { title: 'Custom carousel', value: 'custom' },
            ],
          },
          initialValue: 'countdown',
        }),
        defineField({
          name: 'countdownEnabled',
          title: 'Show countdown timer',
          type: 'boolean',
          description: 'Display the countdown (days, hours, minutes, seconds) on the banner.',
          initialValue: true,
          hidden: ({ parent }) => parent?.bannerType !== 'countdown',
        }),
        defineField({
          name: 'countdownTarget',
          title: 'Countdown Target',
          type: 'string',
          options: { list: [{ title: 'Event Date', value: 'event_date' }, { title: 'Earliest Deadline', value: 'deadline' }] },
          initialValue: 'event_date',
          hidden: ({ parent }) => parent?.bannerType !== 'countdown',
        }),
        defineField({
          name: 'countdownStyle',
          title: 'Countdown Style',
          type: 'string',
          options: { list: [{ title: 'Default', value: 'default' }, { title: 'Minimal', value: 'minimal' }, { title: 'Bold', value: 'bold' }] },
          initialValue: 'default',
          hidden: ({ parent }) => parent?.bannerType !== 'countdown',
        }),
        defineField({
          name: 'showNominationLinks',
          title: 'Show nomination links',
          type: 'boolean',
          initialValue: true,
          hidden: ({ parent }) => parent?.bannerType !== 'countdown',
        }),
        defineField({
          name: 'honoreesTitle',
          title: 'Honorees section title',
          type: 'string',
          description: 'Use {{year}} for event year. Shown for countdown (grid) and announcement banners.',
          placeholder: 'Our Honorees of {{year}}',
          hidden: ({ parent }) => parent?.bannerType === 'custom',
        }),
        defineField({
          name: 'honoreesStyle',
          title: 'Honorees display style',
          type: 'string',
          options: { list: [{ title: 'Grid', value: 'grid' }, { title: 'Cards', value: 'cards' }, { title: 'Minimal', value: 'minimal' }] },
          initialValue: 'grid',
          hidden: ({ parent }) => parent?.bannerType !== 'announcement',
        }),
        defineField({
          name: 'showRegistrationButton',
          title: 'Show registration / CTA button',
          type: 'boolean',
          initialValue: true,
        }),
        defineField({
          name: 'registrationButtonText',
          title: 'Registration button text',
          type: 'string',
          initialValue: 'Register Now',
        }),
        defineField({
          name: 'backgroundImage',
          title: 'Background image',
          type: 'image',
          options: { hotspot: true },
          hidden: ({ parent }) => parent?.bannerType === 'custom',
        }),
        defineField({
          name: 'overlayOpacity',
          title: 'Background overlay opacity',
          type: 'number',
          validation: (rule) => rule.min(0).max(1),
          initialValue: 0.55,
          hidden: ({ parent }) => parent?.bannerType === 'custom',
        }),
        defineField({
          name: 'flyerImage',
          title: 'Banner / flyer image',
          type: 'image',
          description: 'For custom type: main banner image, or first slide if no custom slides.',
          options: { hotspot: true },
          hidden: ({ parent }) => parent?.bannerType !== 'custom',
        }),
        defineField({
          name: 'flyerStyle',
          title: 'Flyer display style',
          type: 'string',
          options: { list: [{ title: 'Card', value: 'card' }, { title: 'Full bleed', value: 'full' }, { title: 'Framed', value: 'framed' }] },
          initialValue: 'card',
          hidden: ({ parent }) => parent?.bannerType !== 'custom',
        }),
        defineField({
          name: 'customSlides',
          title: 'Custom slides',
          type: 'array',
          description: 'Add slides with image, title, subtitle, CTA. Used when Banner Type is Custom.',
          hidden: ({ parent }) => parent?.bannerType !== 'custom',
          of: [
            {
              type: 'object',
              fields: [
                defineField({ name: 'title', title: 'Title', type: 'string' }),
                defineField({ name: 'subtitle', title: 'Subtitle', type: 'string' }),
                defineField({ name: 'image', title: 'Image', type: 'image', options: { hotspot: true } }),
                defineField({ name: 'ctaText', title: 'CTA button text', type: 'string' }),
                defineField({ name: 'ctaUrl', title: 'CTA URL', type: 'url' }),
                defineField({ name: 'accentColor', title: 'Accent color (hex)', type: 'string' }),
              ],
              preview: {
                select: { title: 'title' },
                prepare: ({ title }) => ({ title: title || 'Custom slide' }),
              },
            },
          ],
        }),
        defineField({
          name: 'yearsBadge',
          title: 'Years Strong badge',
          type: 'object',
          fields: [
            defineField({ name: 'enabled', title: 'Show badge', type: 'boolean', initialValue: true }),
            defineField({
              name: 'position',
              title: 'Position',
              type: 'string',
              options: { list: [{ title: 'Top left', value: 'top-left' }, { title: 'Top right', value: 'top-right' }] },
              initialValue: 'top-left',
            }),
            defineField({
              name: 'size',
              title: 'Size',
              type: 'string',
              options: { list: [{ title: 'Small', value: 'sm' }, { title: 'Medium', value: 'md' }, { title: 'Large', value: 'lg' }] },
              initialValue: 'sm',
            }),
          ],
        }),
        defineField({
          name: 'honoreesSection',
          title: 'Honorees (countdown banner)',
          type: 'object',
          description: 'Show honorees grid on countdown banner.',
          fields: [
            defineField({ name: 'enabled', title: 'Show honorees grid', type: 'boolean', initialValue: true }),
            defineField({ name: 'title', title: 'Section title', type: 'string', description: 'Use {{year}} for event year' }),
            defineField({ name: 'style', title: 'Style', type: 'string', options: { list: [{ title: 'Grid', value: 'grid' }, { title: 'Cards', value: 'cards' }, { title: 'Minimal', value: 'minimal' }] }, initialValue: 'grid' }),
            defineField({
              name: 'scrollStyle',
              title: 'Scroll style',
              type: 'string',
              description: 'Infinite = smooth endless vertical. Random rows = each row scrolls horizontally. Random columns = each column scrolls vertically at its own speed.',
              options: {
                list: [
                  { title: 'Infinite (smooth endless)', value: 'infinite' },
                  { title: 'Random rows (each row scrolls horizontally)', value: 'random-rows' },
                  { title: 'Random columns (each column scrolls vertically)', value: 'random-columns' },
                ],
              },
              initialValue: 'infinite',
            }),
          ],
        }),
      ],
    }),
    defineField({
      name: 'description',
      title: 'Event Description',
      type: 'text',
    }),
    defineField({
      name: 'featuredHonorees',
      title: 'Featured Honorees',
      type: 'array',
      of: [
        {
          type: 'reference',
          to: [{type: 'honor'}],
        },
      ],
      description: 'Select honorees to feature prominently on the banner',
    }),
  ],
  preview: {
    select: {
      title: 'eventTitle',
      year: 'eventYear',
      status: 'status',
      date: 'eventDate',
    },
    prepare(selection) {
      const {title, year, status, date} = selection
      return {
        title: `${title} (${year})`,
        subtitle: `${status} - ${date ? new Date(date).toLocaleDateString() : 'No date'}`,
      }
    },
  },
})
