import { defineField, defineType } from 'sanity'

export const awardEventType = defineType({
  name: 'awardEvent',
  title: 'Award Event',
  type: 'document',
  fields: [
    defineField({
      name: 'eventYear',
      title: 'Event Year',
      type: 'number',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'eventTitle',
      title: 'Event Title',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'eventSubtitle',
      title: 'Event Subtitle',
      type: 'string',
    }),
    defineField({
      name: 'eventDate',
      title: 'Event Date',
      type: 'datetime',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'eventLocation',
      title: 'Event Location',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'eventVenue',
      title: 'Event Venue',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'isActive',
      title: 'Is Active Event',
      type: 'boolean',
      description: 'Mark as active to show this event on the website',
      initialValue: true,
    }),
    defineField({
      name: 'status',
      title: 'Event Status',
      type: 'string',
      options: {
        list: [
          {title: 'Nominations Open', value: 'nominations_open'},
          {title: 'Nominations Closed', value: 'nominations_closed'},
          {title: 'Awards Announced', value: 'awards_announced'},
          {title: 'Event Completed', value: 'event_completed'},
          {title: 'Planning', value: 'planning'},
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'yearsStrong',
      title: 'Years Strong',
      type: 'number',
      description: 'Number of years SEED has been running',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'primaryColor',
      title: 'Primary Color',
      type: 'string',
      description: 'Primary color for the event (hex code)',
      initialValue: '#6366f1',
    }),
    defineField({
      name: 'secondaryColor',
      title: 'Secondary Color',
      type: 'string',
      description: 'Secondary color for the event (hex code)',
      initialValue: '#818cf8',
    }),
    defineField({
      name: 'accentColor',
      title: 'Accent Color',
      type: 'string',
      description: 'Accent color for the event (hex code)',
      initialValue: '#4f46e5',
    }),
    defineField({
      name: 'registerEnabled',
      title: 'Registration Enabled',
      type: 'boolean',
      description: 'Enable registration for this event',
      initialValue: false,
    }),
    defineField({
      name: 'registrationUrl',
      title: 'Registration URL',
      type: 'url',
      hidden: ({parent}) => !parent?.registerEnabled,
    }),
    defineField({
      name: 'bannerConfig',
      title: 'Banner Configuration',
      type: 'object',
      description: 'Advanced configuration for the carousel banner',
      fields: [
        defineField({
          name: 'backgroundImage',
          title: 'Background Image',
          type: 'image',
          description: 'Background image for the countdown banner',
          options: {
            hotspot: true,
          },
        }),
        defineField({
          name: 'backgroundOverlay',
          title: 'Background Overlay',
          type: 'object',
          description: 'Overlay settings for background image',
          fields: [
            defineField({
              name: 'enabled',
              title: 'Enable Overlay',
              type: 'boolean',
              initialValue: true,
            }),
            defineField({
              name: 'color',
              title: 'Overlay Color',
              type: 'string',
              description: 'Overlay color (hex code, e.g., #000000)',
              initialValue: '#000000',
            }),
            defineField({
              name: 'opacity',
              title: 'Overlay Opacity',
              type: 'number',
              description: 'Overlay opacity (0-1)',
              initialValue: 0.5,
              validation: (rule) => rule.min(0).max(1),
            }),
          ],
        }),
        defineField({
          name: 'countdownTarget',
          title: 'Countdown Target',
          type: 'string',
          description: 'What date should the countdown display?',
          options: {
            list: [
              {title: 'Event Date', value: 'event_date'},
              {title: 'Earliest Deadline', value: 'deadline'},
            ],
          },
          initialValue: 'event_date',
        }),
        defineField({
          name: 'countdownStyle',
          title: 'Countdown Style',
          type: 'string',
          options: {
            list: [
              {title: 'Default', value: 'default'},
              {title: 'Minimal', value: 'minimal'},
              {title: 'Bold', value: 'bold'},
              {title: 'Gradient', value: 'gradient'},
            ],
          },
          initialValue: 'default',
        }),
        defineField({
          name: 'bannerDesign',
          title: 'Banner Design',
          type: 'string',
          description: 'Choose from 5 modern banner design options',
          options: {
            list: [
              {title: 'Classic Centered', value: 'classic'},
              {title: 'Split Screen', value: 'split'},
              {title: 'Minimalist', value: 'minimalist'},
              {title: 'Hero Style', value: 'hero'},
              {title: 'Card Based', value: 'card'},
            ],
          },
          initialValue: 'classic',
        }),
        defineField({
          name: 'bannerStyle',
          title: 'Banner Style',
          type: 'string',
          options: {
            list: [
              {title: 'Classic', value: 'classic'},
              {title: 'Modern', value: 'modern'},
              {title: 'Elegant', value: 'elegant'},
              {title: 'Minimal', value: 'minimal'},
            ],
          },
          initialValue: 'classic',
        }),
        defineField({
          name: 'textConfiguration',
          title: 'Text Configuration',
          type: 'object',
          description: 'Configure all text elements in the banner',
          fields: [
            defineField({
              name: 'headerText',
              title: 'Header Text',
              type: 'string',
              description: 'Main header text (e.g., "JOIN SEED IN CELEBRATING")',
              initialValue: 'JOIN SEED IN CELEBRATING',
            }),
            defineField({
              name: 'headerTextSize',
              title: 'Header Text Size',
              type: 'string',
              options: {
                list: [
                  {title: 'Small', value: 'text-2xl'},
                  {title: 'Medium', value: 'text-4xl'},
                  {title: 'Large', value: 'text-5xl'},
                  {title: 'Extra Large', value: 'text-6xl'},
                  {title: 'Huge', value: 'text-7xl'},
                ],
              },
              initialValue: 'text-4xl',
            }),
            defineField({
              name: 'headerTextWeight',
              title: 'Header Text Weight',
              type: 'string',
              options: {
                list: [
                  {title: 'Light', value: 'font-light'},
                  {title: 'Normal', value: 'font-normal'},
                  {title: 'Medium', value: 'font-medium'},
                  {title: 'Semibold', value: 'font-semibold'},
                  {title: 'Bold', value: 'font-bold'},
                  {title: 'Extra Bold', value: 'font-extrabold'},
                  {title: 'Black', value: 'font-black'},
                ],
              },
              initialValue: 'font-bold',
            }),
            defineField({
              name: 'subheaderText',
              title: 'Subheader Text',
              type: 'string',
              description: 'Subheader text (e.g., "EXCELLENCE")',
              initialValue: 'EXCELLENCE',
            }),
            defineField({
              name: 'subheaderTextSize',
              title: 'Subheader Text Size',
              type: 'string',
              options: {
                list: [
                  {title: 'Small', value: 'text-xl'},
                  {title: 'Medium', value: 'text-2xl'},
                  {title: 'Large', value: 'text-3xl'},
                  {title: 'Extra Large', value: 'text-4xl'},
                ],
              },
              initialValue: 'text-2xl',
            }),
            defineField({
              name: 'titleTextSize',
              title: 'Event Title Text Size',
              type: 'string',
              options: {
                list: [
                  {title: 'Small', value: 'text-2xl'},
                  {title: 'Medium', value: 'text-3xl'},
                  {title: 'Large', value: 'text-4xl'},
                  {title: 'Extra Large', value: 'text-5xl'},
                ],
              },
              initialValue: 'text-3xl',
            }),
            defineField({
              name: 'locationTextSize',
              title: 'Location Text Size',
              type: 'string',
              options: {
                list: [
                  {title: 'Small', value: 'text-sm'},
                  {title: 'Medium', value: 'text-base'},
                  {title: 'Large', value: 'text-lg'},
                  {title: 'Extra Large', value: 'text-xl'},
                ],
              },
              initialValue: 'text-lg',
            }),
            defineField({
              name: 'countdownLabelSize',
              title: 'Countdown Label Size',
              type: 'string',
              options: {
                list: [
                  {title: 'Extra Small', value: 'text-xs'},
                  {title: 'Small', value: 'text-sm'},
                  {title: 'Medium', value: 'text-base'},
                ],
              },
              initialValue: 'text-xs',
            }),
            defineField({
              name: 'countdownValueSize',
              title: 'Countdown Value Size',
              type: 'string',
              options: {
                list: [
                  {title: 'Small', value: 'text-2xl'},
                  {title: 'Medium', value: 'text-3xl'},
                  {title: 'Large', value: 'text-4xl'},
                  {title: 'Extra Large', value: 'text-5xl'},
                ],
              },
              initialValue: 'text-3xl',
            }),
          ],
        }),
        defineField({
          name: 'layoutConfiguration',
          title: 'Layout Configuration',
          type: 'object',
          description: 'Configure positioning and layout of banner elements',
          fields: [
            defineField({
              name: 'contentPosition',
              title: 'Content Position',
              type: 'string',
              description: 'Where to position the main content',
              options: {
                list: [
                  {title: 'Top Left', value: 'top-left'},
                  {title: 'Top Center', value: 'top-center'},
                  {title: 'Top Right', value: 'top-right'},
                  {title: 'Center Left', value: 'center-left'},
                  {title: 'Center', value: 'center'},
                  {title: 'Center Right', value: 'center-right'},
                  {title: 'Bottom Left', value: 'bottom-left'},
                  {title: 'Bottom Center', value: 'bottom-center'},
                  {title: 'Bottom Right', value: 'bottom-right'},
                ],
              },
              initialValue: 'center',
            }),
            defineField({
              name: 'countdownPosition',
              title: 'Countdown Position',
              type: 'string',
              description: 'Where to position the countdown timer',
              options: {
                list: [
                  {title: 'Above Title', value: 'above-title'},
                  {title: 'Below Title', value: 'below-title'},
                  {title: 'Left Side', value: 'left-side'},
                  {title: 'Right Side', value: 'right-side'},
                  {title: 'Top', value: 'top'},
                  {title: 'Bottom', value: 'bottom'},
                ],
              },
              initialValue: 'below-title',
            }),
            defineField({
              name: 'eventDetailsPosition',
              title: 'Event Details Position',
              type: 'string',
              description: 'Where to position event details',
              options: {
                list: [
                  {title: 'Below Countdown', value: 'below-countdown'},
                  {title: 'Above Countdown', value: 'above-countdown'},
                  {title: 'Left Side', value: 'left-side'},
                  {title: 'Right Side', value: 'right-side'},
                  {title: 'Bottom', value: 'bottom'},
                ],
              },
              initialValue: 'below-countdown',
            }),
            defineField({
              name: 'buttonPosition',
              title: 'Button Position',
              type: 'string',
              description: 'Where to position the registration button',
              options: {
                list: [
                  {title: 'Center', value: 'center'},
                  {title: 'Left', value: 'left'},
                  {title: 'Right', value: 'right'},
                  {title: 'Below Details', value: 'below-details'},
                  {title: 'Above Details', value: 'above-details'},
                ],
              },
              initialValue: 'center',
            }),
            defineField({
              name: 'spacing',
              title: 'Spacing',
              type: 'object',
              description: 'Configure spacing between elements',
              fields: [
                defineField({
                  name: 'headerSpacing',
                  title: 'Header Spacing',
                  type: 'number',
                  description: 'Spacing below header (in rem)',
                  initialValue: 2,
                }),
                defineField({
                  name: 'countdownSpacing',
                  title: 'Countdown Spacing',
                  type: 'number',
                  description: 'Spacing around countdown (in rem)',
                  initialValue: 2,
                }),
                defineField({
                  name: 'detailsSpacing',
                  title: 'Details Spacing',
                  type: 'number',
                  description: 'Spacing around event details (in rem)',
                  initialValue: 2,
                }),
              ],
            }),
          ],
        }),
        defineField({
          name: 'registrationButton',
          title: 'Registration Button',
          type: 'object',
          description: 'Configuration for the event registration button',
          fields: [
            defineField({
              name: 'text',
              title: 'Button Text',
              type: 'string',
              initialValue: 'Register Now',
            }),
            defineField({
              name: 'backgroundColor',
              title: 'Background Color',
              type: 'string',
              description: 'Button background color (hex code)',
            }),
            defineField({
              name: 'textColor',
              title: 'Text Color',
              type: 'string',
              description: 'Button text color (hex code)',
              initialValue: '#ffffff',
            }),
            defineField({
              name: 'hoverColor',
              title: 'Hover Color',
              type: 'string',
              description: 'Button hover color (hex code)',
            }),
            defineField({
              name: 'size',
              title: 'Button Size',
              type: 'string',
              options: {
                list: [
                  {title: 'Small', value: 'small'},
                  {title: 'Medium', value: 'medium'},
                  {title: 'Large', value: 'large'},
                  {title: 'Extra Large', value: 'xlarge'},
                ],
              },
              initialValue: 'medium',
            }),
            defineField({
              name: 'shape',
              title: 'Button Shape',
              type: 'string',
              options: {
                list: [
                  {title: 'Rounded', value: 'rounded'},
                  {title: 'Rounded Full', value: 'rounded-full'},
                  {title: 'Square', value: 'square'},
                  {title: 'Pill', value: 'pill'},
                ],
              },
              initialValue: 'rounded-full',
            }),
            defineField({
              name: 'position',
              title: 'Button Position',
              type: 'string',
              options: {
                list: [
                  {title: 'Center', value: 'center'},
                  {title: 'Left', value: 'left'},
                  {title: 'Right', value: 'right'},
                ],
              },
              initialValue: 'center',
            }),
          ],
        }),
        defineField({
          name: 'honoreesSection',
          title: 'Honorees Section Configuration',
          type: 'object',
          description: 'Configure the "Meet Our Honorees" section',
          fields: [
            defineField({
              name: 'enabled',
              title: 'Show Honorees Section',
              type: 'boolean',
              description: 'Enable or disable the honorees section in the banner carousel',
              initialValue: true,
            }),
            defineField({
              name: 'style',
              title: 'Honorees Section Style',
              type: 'string',
              description: 'Choose the style for displaying honorees',
              options: {
                list: [
                  {title: 'Modern Carousel', value: 'modern'},
                  {title: 'Grid Layout', value: 'grid'},
                  {title: 'Card Stack', value: 'cards'},
                  {title: 'Minimal List', value: 'minimal'},
                  {title: 'Gallery View', value: 'gallery'},
                ],
              },
              initialValue: 'modern',
            }),
            defineField({
              name: 'title',
              title: 'Section Title',
              type: 'string',
              description: 'Title for the honorees section',
              initialValue: 'Meet Our Honorees',
            }),
            defineField({
              title: 'Background Type',
              name: 'backgroundType',
              type: 'string',
              options: {
                list: [
                  {title: 'Color', value: 'color'},
                  {title: 'Image', value: 'image'},
                  {title: 'Gradient', value: 'gradient'},
                  {title: 'None', value: 'none'},
                ],
              },
              initialValue: 'none',
            }),
            defineField({
              name: 'backgroundColor',
              title: 'Background Color',
              type: 'string',
              description: 'Background color for the honorees section (hex code)',
              hidden: ({parent}) => parent?.backgroundType !== 'color',
            }),
            defineField({
              name: 'backgroundImage',
              title: 'Background Image',
              type: 'image',
              description: 'Background image for the honorees section',
              options: {
                hotspot: true,
              },
              hidden: ({parent}) => parent?.backgroundType !== 'image',
            }),
            defineField({
              name: 'backgroundGradient',
              title: 'Background Gradient',
              type: 'object',
              description: 'Gradient background settings',
              hidden: ({parent}) => parent?.backgroundType !== 'gradient',
              fields: [
                defineField({
                  name: 'startColor',
                  title: 'Start Color',
                  type: 'string',
                  description: 'Gradient start color (hex code)',
                }),
                defineField({
                  name: 'endColor',
                  title: 'End Color',
                  type: 'string',
                  description: 'Gradient end color (hex code)',
                }),
                defineField({
                  name: 'direction',
                  title: 'Direction',
                  type: 'string',
                  options: {
                    list: [
                      {title: 'To Right', value: 'to right'},
                      {title: 'To Bottom', value: 'to bottom'},
                      {title: 'To Bottom Right', value: 'to bottom right'},
                      {title: 'Radial', value: 'radial'},
                    ],
                  },
                  initialValue: 'to right',
                }),
              ],
            }),
            defineField({
              name: 'overlay',
              title: 'Background Overlay',
              type: 'object',
              description: 'Overlay settings for background',
              fields: [
                defineField({
                  name: 'enabled',
                  title: 'Enable Overlay',
                  type: 'boolean',
                  initialValue: false,
                }),
                defineField({
                  name: 'color',
                  title: 'Overlay Color',
                  type: 'string',
                  description: 'Overlay color (hex code)',
                  initialValue: '#000000',
                }),
                defineField({
                  name: 'opacity',
                  title: 'Overlay Opacity',
                  type: 'number',
                  description: 'Overlay opacity (0-1)',
                  initialValue: 0.5,
                  validation: (rule) => rule.min(0).max(1),
                }),
              ],
            }),
          ],
        }),
        defineField({
          name: 'yearsBadge',
          title: 'Years Strong Badge Configuration',
          type: 'object',
          description: 'Configure the "Years Strong" badge display',
          fields: [
            defineField({
              name: 'enabled',
              title: 'Show Badge',
              type: 'boolean',
              description: 'Enable or disable the years strong badge',
              initialValue: true,
            }),
            defineField({
              name: 'position',
              title: 'Badge Position',
              type: 'string',
              description: 'Where to position the badge on the banner',
              options: {
                list: [
                  {title: 'Top Left', value: 'top-left'},
                  {title: 'Top Right', value: 'top-right'},
                  {title: 'Bottom Left', value: 'bottom-left'},
                  {title: 'Bottom Right', value: 'bottom-right'},
                  {title: 'Top Center', value: 'top-center'},
                  {title: 'Bottom Center', value: 'bottom-center'},
                  {title: 'Center', value: 'center'},
                ],
              },
              initialValue: 'top-left',
            }),
            defineField({
              name: 'style',
              title: 'Badge Style',
              type: 'string',
              description: 'Visual style of the badge',
              options: {
                list: [
                  {title: 'Default (Rotating)', value: 'default'},
                  {title: 'Static', value: 'static'},
                  {title: 'Minimal', value: 'minimal'},
                  {title: 'Bold', value: 'bold'},
                  {title: 'Elegant', value: 'elegant'},
                ],
              },
              initialValue: 'default',
            }),
            defineField({
              name: 'size',
              title: 'Badge Size',
              type: 'string',
              options: {
                list: [
                  {title: 'Small', value: 'sm'},
                  {title: 'Medium', value: 'md'},
                  {title: 'Large', value: 'lg'},
                  {title: 'Extra Large', value: 'xl'},
                ],
              },
              initialValue: 'sm',
            }),
            defineField({
              name: 'text',
              title: 'Badge Text',
              type: 'string',
              description: 'Text to display below the number (e.g., "Years Strong")',
              initialValue: 'Years Strong',
            }),
            defineField({
              name: 'primaryColor',
              title: 'Primary Color',
              type: 'string',
              description: 'Primary accent color for the badge (hex code)',
              initialValue: '#F9D773',
            }),
            defineField({
              name: 'secondaryColor',
              title: 'Secondary Color',
              type: 'string',
              description: 'Secondary accent color for the badge (hex code)',
              initialValue: '#C9A227',
            }),
            defineField({
              name: 'backgroundColor',
              title: 'Background Color',
              type: 'string',
              description: 'Background color of the badge (hex code)',
              initialValue: '#0F2A5A',
            }),
            defineField({
              name: 'pulseEffect',
              title: 'Pulse Effect',
              type: 'boolean',
              description: 'Enable pulsing animation on the badge',
              initialValue: true,
            }),
            defineField({
              name: 'rotateEffect',
              title: 'Rotate Effect',
              type: 'boolean',
              description: 'Enable rotating animation on the badge border',
              initialValue: true,
            }),
          ],
        }),
      ],
    }),
    defineField({
      name: 'description',
      title: 'Event Description',
      type: 'text',
    }),
    defineField({
      name: 'featuredHonorees',
      title: 'Featured Honorees',
      type: 'array',
      of: [
        {
          type: 'reference',
          to: [{type: 'honor'}],
        },
      ],
      description: 'Select honorees to feature prominently on the banner',
    }),
  ],
  preview: {
    select: {
      title: 'eventTitle',
      year: 'eventYear',
      status: 'status',
      date: 'eventDate',
    },
    prepare(selection) {
      const {title, year, status, date} = selection
      return {
        title: `${title} (${year})`,
        subtitle: `${status} - ${date ? new Date(date).toLocaleDateString() : 'No date'}`,
      }
    },
  },
})
